//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>ContentPage</summary>
	[PublishedContentModel("contentPage")]
	public partial class ContentPage : PublishedContentModel, IContentBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Dynamic body text
		///</summary>
		[ImplementPropertyType("dynamicBodyText")]
		public Newtonsoft.Json.Linq.JToken DynamicBodyText
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("dynamicBodyText"); }
		}

		///<summary>
		/// Numbers
		///</summary>
		[ImplementPropertyType("numbers")]
		public IEnumerable<IPublishedContent> Numbers
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("numbers"); }
		}

		///<summary>
		/// Picture links
		///</summary>
		[ImplementPropertyType("pictureLinks")]
		public IEnumerable<IPublishedContent> PictureLinks
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("pictureLinks"); }
		}

		///<summary>
		/// Body text
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return Umbraco.Web.PublishedContentModels.ContentBase.GetBodyText(this); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.ContentBase.GetHeadline(this); }
		}
	}
}
